name: Stefan Schwartz
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
description: An ordinary blog (this) of an ordinary student (me) at an unusual university (FIIT)
url: http://pistik.github.io

gems:
  - jemoji
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-redirect-from

collections:
  projects:
    output: true
    permalink: /projects/:path/