name: Stefan Schwartz
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
description: An ordinary blog of an ordinary student at an unusual university
url: http://pistik.github.io
gems:
  - jemoji
  - jekyll-mentions
  - jekyll-sitemap
collections:
  colprojects:
    output: true
    permalink: /projects/:path/